-- Generated by seed-cards-with-assets.ts
-- Run: bunx wrangler d1 execute trading-cards --local --file=./scripts/update-cards-assets.sql

-- Delete existing cards and gacha_rates (keep gacha_packs)
DELETE FROM gacha_rates;
DELETE FROM cards;

-- Insert cards with asset_id
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (1, '炎猫フレイム', 'Style: Phoenix, Anim: Blaze', 'phoenix', 'fire', '7f688b8b-ad97-44d8-8a2f-bc05cf8be741.png', '燃え盛る炎を纏った猫', 'Flame', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (2, '溶岩の守護獣', 'Style: Magma, Anim: Flow', 'magma', 'fire', '6cf8b1d9-d2e7-43f6-9520-69c87e56f4b8.png', '溶岩を操る古代の守護者', 'Mountain', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (3, '紅蓮の戦士', 'Style: Crimson, Anim: Strike', 'animated-blaze', 'fire', 'd92c919d-5936-4617-aa07-7a1fd1e22af5.png', '紅蓮の炎で敵を焼き尽くす戦士', 'Swords', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (4, '虹色の妖精', 'Style: Rainbow, Anim: Flutter', 'rainbow', 'holo', 'c68f9229-31cc-427f-8170-14ffa783c5e2.png', '虹の架け橋を渡る小さな妖精', 'Rainbow', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (5, '花園の精霊', 'Style: Garden, Anim: Bloom', 'hearts', 'bubblegum', 'f7eada7f-93d4-4dbb-957a-8eb02609871f.png', '花々に囲まれた可愛い精霊', 'Flower2', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (6, 'ゆめかわユニコーン', 'Style: Dream, Anim: Gallop', 'candy-swirl', 'cotton-candy', '72bbb258-c453-4fce-bffe-52f52a67313c.png', 'パステルカラーの夢かわユニコーン', 'Sparkles', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (7, '氷結の騎士', 'Style: Frost, Anim: Freeze', 'frozen', 'ice', '35cb8af1-03ea-4246-a884-f6349308b64d.png', '氷の剣を振るう冷徹な騎士', 'Sword', 'cool');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (8, 'サイバー忍者', 'Style: Cyber, Anim: Dash', 'neon-grid', 'cyberpunk', 'd9b221d8-5c75-4d4c-b1da-89db81f23758.png', '電脳世界を駆ける忍者', 'Zap', 'cool');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (9, '深淵の魔王', 'Style: Abyss, Anim: Emerge', 'abyssal', 'void-script', '98ac36f2-c2c2-4219-82de-4ba556e0be10.png', '深淵から現れた魔界の王', 'Skull', 'dark');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (10, '闇夜の吸血鬼', 'Style: Vampire, Anim: Bite', 'shadow-warp', 'shadow-whispers', '9f79bc64-47cd-42c2-bf25-cf32c3e36d90.png', '闇夜に潜む不死の吸血鬼', 'Moon', 'dark');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (11, '聖光の天使', 'Style: Holy, Anim: Descend', 'basic', 'gold', '12ff18db-6f79-4824-8cfa-bfc39fb47996.png', '聖なる光を纏った天使', 'Sparkles', 'white');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (12, '純白のユニコーン', 'Style: Pure, Anim: Gallop', 'rainbow', 'holo', 'a74e7509-64b8-4623-867a-c1348858263d.png', '純粋な心を持つ者だけが見えるユニコーン', 'Sparkles', 'white');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (13, '銀狼の遠吠え', 'Style: Silver, Anim: Howl', 'silver', 'steel', 'f41472ae-b5c9-44b9-b039-3c1223378882.jpg', '月夜に吠える銀色の狼', 'Moon', 'white');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (14, '灼熱の龍', 'Style: Inferno, Anim: Roar', 'inferno', 'plasma', '6d3096d2-0c6d-4140-8529-035aa0bfc3c7.png', '灼熱の息を吐く伝説の龍', 'Flame', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (15, '朱雀の化身', 'Style: Vermilion, Anim: Soar', 'phoenix', 'gold', 'e3875f2f-e273-4f6f-835a-aa3932da8232.png', '四神の一柱、朱雀の化身', 'Bird', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (16, 'シャボン玉の踊り子', 'Style: Bubble, Anim: Float', 'bubbles', 'holo', '91425bdb-a02b-47e8-8877-f2a10a2f0506.png', 'シャボン玉と踊る少女', 'Circle', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (17, 'プリンセスの午後', 'Style: Royal, Anim: Wave', 'glitter', 'bubblegum', '317ec027-6122-4e77-be4f-d6f513bf3d30.png', 'お茶会を楽しむ小さなプリンセス', 'Crown', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (18, 'メカニカル・ドラゴン', 'Style: Mech, Anim: Activate', 'carbon', 'cyberpunk', 'd38f9f76-e0b9-4d37-9ca7-98bcff2798f8.png', '機械仕掛けの龍', 'Cog', 'cool');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (19, 'ネオン街の狩人', 'Style: Neon, Anim: Hunt', 'neon-grid', 'neon', 'a937e62e-904a-43f5-93d2-cf83d15afc8d.png', 'ネオンの街を徘徊する狩人', 'Target', 'cool');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (20, '死神の鎌', 'Style: Reaper, Anim: Swing', 'eclipsed', 'void-script', '54600cd2-bd1a-430b-b09f-f9956b7c0e54.png', '魂を刈り取る死神', 'Skull', 'dark');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (21, '堕天使ルシファー', 'Style: Fallen, Anim: Descend', 'abyssal', 'void-script', 'da81c247-94c5-4430-bc89-588cdaceb980.png', '天から堕ちた美しき天使', 'Feather', 'dark');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (22, '冥界の番犬', 'Style: Underworld, Anim: Guard', 'corrupted', 'shadow-whispers', '7e26d785-bee1-4c66-9aac-221690a04b6d.png', '冥界の門を守る三つ首の犬', 'Dog', 'dark');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (23, '白虎の化身', 'Style: Byakko, Anim: Roar', 'silver', 'steel', '9008889b-346e-4958-b1dd-5ff468a64877.png', '四神の一柱、白虎の化身', 'Cat', 'white');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (24, '満月の祭司', 'Style: Moon, Anim: Chant', 'silver', 'holo', '160b76a0-6f3c-4d72-9bce-eeb108f60d74.png', '満月の力を借りる祭司', 'Moon', 'white');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (25, '業火の魔術師', 'Style: Hellfire, Anim: Cast', 'hellfire', 'fire', '971c7951-9251-4445-9ff8-a816987a9ab5.png', '業火を操る闇の魔術師', 'Wand2', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (26, '火山の巨人', 'Style: Volcanic, Anim: Erupt', 'magma', 'plasma', '2691d553-141f-4b25-a8d0-097e6d63b89c.png', '火山から生まれた巨人', 'Mountain', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (27, '炎帝の剣', 'Style: Emperor, Anim: Slash', 'blaze', 'gold', '54a718a0-01a5-4e79-9c25-d734db244131.png', '炎帝が振るう伝説の剣', 'Sword', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (28, '星空のペガサス', 'Style: Starlight, Anim: Fly', 'sparkle', 'holo', 'acee0567-a4a0-426e-9168-64d48d52a51c.png', '星空を駆けるペガサス', 'Star', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (29, 'お花畑のうさぎ', 'Style: Flower, Anim: Hop', 'hearts', 'cotton-candy', '66b42217-487c-4459-b1e5-9320b60bb18f.png', 'お花畑で遊ぶうさぎ', 'Rabbit', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (30, '量子コンピュータ', 'Style: Quantum, Anim: Process', 'circuit', 'neon', 'b1e27a5a-6a4d-47b5-99ac-0fbcb5b3745e.png', '量子の力を持つマシン', 'Cpu', 'cool');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (31, 'タイムトラベラー', 'Style: Time, Anim: Warp', 'animated-warp', 'cyberpunk', '9b6094dc-16aa-457e-ac8f-44b55778deb0.png', '時空を超える旅人', 'Clock', 'cool');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (32, '闇の召喚師', 'Style: Dark, Anim: Summon', 'dark-matter', 'void-script', 'a098e88a-c5d5-4e6f-8184-ffce002f86b9.png', '闇の生物を召喚する者', 'Ghost', 'dark');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (33, '呪いの人形', 'Style: Curse, Anim: Haunt', 'shadow-warp', 'shadow-whispers', 'ed00db1b-b5a1-48ca-bad0-5676bd7bffce.png', '呪いが宿った人形', 'Ghost', 'dark');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (34, '神聖なる龍', 'Style: Divine, Anim: Ascend', 'gold', 'gold', '9c515767-cbba-47aa-a91b-0649cdca0385.png', '神聖なる力を持つ白い龍', 'Star', 'white');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (35, '光の精霊王', 'Style: Light, Anim: Radiate', 'crystal', 'neon', 'bce9b9cb-12e1-4bc5-a357-1b9b1dd2eb7d.png', '光の力を司る精霊の王', 'Sun', 'white');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (36, '太陽の戦士', 'Style: Solar, Anim: Blaze', 'plasmatic', 'fire', 'a0429a6d-3e13-4a3d-8790-12e175eabe76.png', '太陽の力を宿した戦士', 'Sun', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (37, '不死鳥の卵', 'Style: Phoenix, Anim: Hatch', 'ember', 'gold', 'd01c1b9b-bcac-49ba-9210-c00cb66e330d.png', '伝説の不死鳥の卵', 'Egg', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (38, '炎の精霊', 'Style: Fire, Anim: Dance', 'phoenix', 'plasma', '7c3369ac-9dd7-4c10-8c4e-1b78368d8a13.png', '炎と共に踊る精霊', 'Flame', 'hot');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (39, 'キャンディの妖精', 'Style: Candy, Anim: Sprinkle', 'sparkle-dust', 'bubblegum', '4ce9a5a4-767c-458f-8ef2-f547404e7f52.png', 'キャンディを振りまく妖精', 'Candy', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (40, '月のうさぎ', 'Style: Lunar, Anim: Jump', 'glitter', 'cotton-candy', '29b09ac9-cfb7-4cca-ac6c-179e2cfaa856.png', '月に住むうさぎ', 'Rabbit', 'cute');
INSERT INTO cards (id, name, type, holo_type, text_style, asset_id, description, icon_name, rarity) VALUES (41, '虹のスライム', 'Style: Rainbow, Anim: Bounce', 'rainbow', 'holo', '51655bde-fb09-49fc-bf97-1b963cff742a.png', '虹色に輝くスライム', 'Droplet', 'cute');

-- Re-insert gacha rates for all packs
INSERT INTO gacha_rates (pack_id, card_id, weight, is_pickup) SELECT 'standard', id, 100, 0 FROM cards;
INSERT INTO gacha_rates (pack_id, card_id, weight, is_pickup) SELECT 'premium', id, 100, 0 FROM cards;
INSERT INTO gacha_rates (pack_id, card_id, weight, is_pickup) SELECT 'hot-pack', id, 100, 0 FROM cards WHERE rarity = 'hot';
INSERT INTO gacha_rates (pack_id, card_id, weight, is_pickup) SELECT 'cute-pack', id, 100, 0 FROM cards WHERE rarity = 'cute';
INSERT INTO gacha_rates (pack_id, card_id, weight, is_pickup) SELECT 'cool-pack', id, 100, 0 FROM cards WHERE rarity = 'cool';
INSERT INTO gacha_rates (pack_id, card_id, weight, is_pickup) SELECT 'dark-pack', id, 100, 0 FROM cards WHERE rarity = 'dark';
INSERT INTO gacha_rates (pack_id, card_id, weight, is_pickup) SELECT 'white-pack', id, 100, 0 FROM cards WHERE rarity = 'white';
